name: Deploy to DEV Tekdi-OU
on: 
  push: 
    branches:
      - main
jobs:
  build:
    name: Generate Build and Deploy to PROD
   # environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 21.0.0
          
      - name: Generate React Build
        run: |
          yarn install
          yarn workspace @shiksha/common-lib build
          yarn install
          yarn build
          
      - name: Create Lerna Bundles for Submodules
        run: |
          sh ./scripts/pack-prod-build.sh

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_TEKDI_OU }}
          known_hosts: unnecessary

      - name: Add Entry to Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT_TEKDI_OU}} -H ${{ secrets.SSH_HOST_TEKDI_OU }}  >> ~/.ssh/known_hosts

      - name: Copy Build Artifact using Rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT_TEKDI_OU }}" shiksha-ui.tar ${{ secrets.SSH_USER_TEKDI_OU }}@${{ secrets.SSH_HOST_TEKDI_OU }}:/ubuntu/shiksha-ui.tar

      - name: Unzip Artifact to Correct Locations to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_TEKDI_OU }}
          username: ${{ secrets.SSH_USER_TEKDI_OU }}
          key: ${{ secrets.SSH_PRIVATE_KEY_TEKDI_OU }}
          script: |
            cd /root
            tar -xvf shiksha-ui.tar -C /var/www/shiksha.tekdinext.com/public
